include: package:lint/strict.yaml

linter:
  rules:
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_renaming_method_parameters: true
    flutter_style_todos: true
    only_throw_errors: true
    prefer_single_quotes: true
    sort_constructors_first: true
    unawaited_futures: true
    unnecessary_lambdas: true
    use_decorated_box: true

    # shorter and prettier syntax
    cascade_invocations: true
    prefer_expression_function_bodies: true

    # Key is important for tests
    use_key_in_widget_constructors: true

analyzer:
  plugins:
    - dart_code_linter
  language:
    # Already in lint package
    # strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
    - test/**
    - lib/**.g.dart
    - packages/**
    - lib/core/prisma/**

  errors:
    unused_local_variable: warning
    missing_required_param: error
    unused_field: warning
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

dart_code_linter:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 5
    source-lines-of-code: 100
    halstead-volume: 150

  metrics-exclude:
    - build/**
    - lib/**.g.dart
    - lib/core/prisma/**
    # Test's folder
    - test/**
    - packages/**
  rules:
    - avoid-border-all
    - avoid-cascade-after-if-null
    - avoid-collection-methods-with-unrelated-types
    - avoid-double-slash-imports
    - avoid-duplicate-exports
    - avoid-global-state

    # - avoid-ignoring-return-values

    - avoid-nested-conditional-expressions:
        acceptable-level: 3
    - avoid-redundant-async
    - avoid-returning-widgets
    - avoid-throw-in-catch-block
    - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - avoid-unrelated-type-assertions
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unnecessary-conditionals
    - avoid-unused-parameters
    - avoid-wrapping-in-padding
    - no-boolean-literal-compare
    - no-empty-block
    # - no-equal-arguments:
    #     ignored-parameters:
    #       - height
    #       - width
    #       - minHeight
    #       - minWidth
    #       - left
    #       - right
    - no-equal-then-else
    - no-object-declaration
    - prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    - prefer-enums-by-name
    - prefer-extracting-callbacks
    - prefer-first
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-last
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - prefer-using-list-view

    # Use state.mounted or context.isMounted
    - use-setstate-synchronously
